// Generated by CoffeeScript 1.3.3
(function() {

  head.js(!document.body.classList ? 'lib/js/classList.js' : null);

  head.js('/js/lib/reveal.js', function() {
    var query;
    query = {};
    location.search.replace(/[A-Z0-9]+?=(\w*)/gi, function(a) {
      return query[a.split('=').shift()] = a.split('=').pop();
    });
    return Reveal.initialize({
      controls: true,
      progress: true,
      history: true,
      theme: query.theme || 'default',
      transition: query.transition || 'default'
    });
  });

  head.js('/js/lib/highlight.js', function() {
    return hljs.initHighlightingOnLoad();
  });

}).call(this);
